import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  
  cloudSidebar: [{type: 'autogenerated', dirName: 'cloud'}],
  companySidebar: [{type: 'autogenerated', dirName: 'company'}],
  privacySidebar: [{type: 'autogenerated', dirName: 'privacy'}],
  securitySidebar: [{type: 'autogenerated', dirName: 'security'}],
  tosSidebar: [{type: 'autogenerated', dirName: 'tos'}],
  isoSidebar: [{type: 'autogenerated', dirName: 'iso'}],

};

export default sidebars;
