import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  
  cloudSidebar: [{type: 'autogenerated', dirName: 'cloud'}],
  communityidebar: [{type: 'autogenerated', dirName: 'community'}],
  privacySidebar: [{type: 'autogenerated', dirName: 'privacy'}],
  securitySidebar: [{type: 'autogenerated', dirName: 'security'}],
  tosSidebar: [{type: 'autogenerated', dirName: 'tos'}],

};

export default sidebars;
